spring.application.name=BookMyShow

spring.datasource.url=jdbc:mysql://localhost:3306/bms_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Vishal@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Razorpay Configuration
razorpay.key_id=rzp_test_S3OTgBs305vzsD
razorpay.key_secret=WyhO3S3LIAozahSy8Fuz31aK

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patelcode24@gmail.com
spring.mail.password=yovx msjq sgcd xzav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
